### ISSUE TITLE
ImportError: cannot import name Feature from setuptools

### ISSUE THREAD

**Issue by juippis** [zackw/mini-amf#1]
After upgrading setuptools to 46 installing mini-amf is impossible due to Feature being dropped upstream. 

https://aur.archlinux.org/cgit/aur.git/tree/fix-setup-py38.patch?h=python-mini-amf I found this patch that seems to be working, but I don't know enough python to determine whether it causes runtime issues.

This should probably still be best fixed here.
